---
user: "{{ lookup('vars', 'ansible_user') }}"
aws_access_key: "{{ lookup('env','AWS_ACCESS_KEY_ID') }}"
aws_secret_key: "{{ lookup('env','AWS_SECRET_ACCESS_KEY') }}"
frontend_apikey: "{{ lookup('env','FRONTEND_APIKEY') }}"
slack_webhook: "{{ lookup('env','SLACK_WEBHOOK') }}"
slack_channel: "{{ lookup('env','SLACK_CHANNEL') }}"
mysql_user: "{{ lookup('env','MYSQL_USER') }}"
mysql_password: "{{ lookup('env','MYSQL_PASSWORD') }}"
azure_pat: "{{ lookup('env','AZURE_PAT') }}"
azure_org: "{{ lookup('env','AZURE_ORG') }}"
azure_prj: "{{ lookup('env','AZURE_PRJ') }}"
azure_callback_pipeline_id: "{{ lookup('env','AZURE_CALLBACK_PIPELINE_ID') }}"
bucket_annotation: "forome-annotation"
bucket_dataset: "forome-dataset-public"
endpoint_url: "https://s3.us-south.cloud-object-storage.appdomain.cloud"
data_dir: "/data"
cases_dir: "{{ data_dir }}/cases"
download_dir: "{{ data_dir }}/download"
astorage_dir: "{{ data_dir }}/astorage"
annotation_dir: "{{ data_dir }}/annotation"
py_venv: "{{ astorage_dir }}/venv"
py_requirements: "/data/astorage/Anfisa-Annotations/requirements.txt"
annotation_src: "{{ astorage_dir }}/Anfisa-Annotations/annotation-service"
mysql_host: "localhost"
mysql_port: 3306
uwsgi_host: "localhost"
uwsgi_port: 8290
nginx_host: "localhost"
nginx_port: 80
# forome_tools_whl: "forome_tools-0.1.8-py3-none-any.whl"
# forome_tools_url: "https://github.com/ForomePlatform/forome_misc_tools/releases/download/v0.1.8/forome_tools-0.1.8-py3-none-any.whl.gz"
annotation_git_repo: "https://github.com/ForomePlatform/Anfisa-Annotations.git"
annotation_git_branch: "master"
forome_tools_git_repo: "https://github.com/ForomePlatform/forome_misc_tools"
data:
  - schema.tar.gz
  - rdbs.tar.gz
  - database.tar.gz
datasets:
  - NA12878_wgs_hlpanel.tar.gz
  - pgp3140_wgs_hlpanel.tar.gz
  - pgp3140_wgs_nist1696.tar.gz
  - pgp3140_wgs_rtg1997.tar.gz
  - pgp3140_wgs_nist-v3.3.2.tar.gz