---
# - name: Create /data/mysql and /var/lib/mysql
#   file:
#     path: "{{ item }}"
#     state: directory
#   with_items:
#   - '/data/mysql'
#   - '/var/lib/mysql'
# - name: Mount /var/lib/mysql to /data/mysql
#   ansible.posix.mount:
#     path: /data/mysql
#     src: /var/lib/mysql
#     opts: bind
#     state: mounted
#     fstype: none

- name: Unarchive dump
  unarchive:
    src: /data/download/mysqldump.tar.gz
    dest: /data/download
    remote_src: yes
  register: awscli_unarchive

- name: Restore database
  bacome: true
  shell: mysql < /data/download/mysqldump.sql