---
- name: Install mysql-connector-java
  become: true
  apt:
    deb: "https://downloads.mysql.com/archives/get/p/3/file/mysql-connector-java_8.0.27-1ubuntu20.04_all.deb"
    state : present

- name: Install dependencies
  become: true
  pip:
    name: docker

- name: Start gradle container
  community.docker.docker_container:
    name: gradle
    image: gradle:4.8-jdk-slim
    auto_remove: yes
    user: root
    volumes:
    - "{{ volume_path }}:/home/gradle"
    command: >
      /bin/bash -c "gradle clean --refresh-dependencies && gradle build -Pfilename=annotation.jar --refresh-dependencies"
  register: gradle
- debug:
    msg: gradle