---
- name: Install nginx
  become: true
  apt:
    name: nginx
    update_cache: yes
    state: latest
  notify: start nginx

- name: Generate nginx config
  become: true
  template:
    src: uwsgi.conf.j2
    dest: /etc/nginx/conf.d/uwsgi.conf
  notify: restart nginx