---
- name: "Install dependencies"
  become: true
  apt:
    name: "{{ item }}"
    update_cache: yes
    state: present
  loop:
    - python3
    - python3-pip

- name: "Install boto3 and botocore modules"
  pip:
    name: "{{ item }}"
    state: present
  loop:
    - boto3
    - botocore
