---
- hosts: all
  gather_facts: no

  pre_tasks:

    - name: "Wait for SSH"
      wait_for:
        port: 22
        host: "{{ (ansible_ssh_host|default(ansible_host))|default(inventory_hostname) }}"
        search_regex: OpenSSH
        timeout: 600
      connection: local
    
    - debug:
        msg: |
          env MYSQL_USER: {{ lookup('env','MYSQL_USER') }}
          ansible_ssh_host: {{ ansible_ssh_host }}

    - name: "Gathering facts"
      setup:

  roles:
    # - user
    # - apt
    # - docker
    # - awscli
    # - mysql
    # - copy-data
    # - copy-dataset
    # - nginx
    # - python
    # - astorage
    - annotation