---
- hosts: all
  gather_facts: no
  pre_tasks:
  - name: Wait for SSH
    wait_for:
      port: 22
      host: "{{ (ansible_ssh_host|default(ansible_host))|default(inventory_hostname) }}"
      search_regex: OpenSSH
      timeout: 60
    connection: local
  - name: Gathering facts
    setup:
  roles:
  - user
  - apt
  - docker
  - awscli
  - copy-data
  - copy-dataset
  - mysql
  - nginx
  - python
  - astorage
  - annotation
  # - build-jar