---
- hosts: all
  gather_facts: no

  pre_tasks:

    - name: "Wait for SSH"
      wait_for:
        port: 22
        host: "{{ (ansible_ssh_host|default(ansible_host))|default(inventory_hostname) }}"
        search_regex: OpenSSH
        timeout: 600
      connection: local

    - name: "Gathering facts"
      setup:

  roles:
    - user
    - apt
    - docker
    - prepdir
    - pipdep
    - awscli
    - mysql
    - data
    - callback
    - datasets
    - nginx
    - python
    - astorage
    - annotation