---
- name: Create user {{ user }}
  become: true
  user:
    name: "{{ user }}"
    shell: /bin/bash
    groups: sudo
    state: present

- name: Add authorized keys
  become: true
  authorized_key:
    user: "{{ user }}"
    key: "{{ lookup('file', item) }}"
    state: present
  with_fileglob:
    - "*.pub"

- name: Modify /etc/sudoers
  become: true
  lineinfile:
    dest: /etc/sudoers
    regexp: "^%sudo"
    line: "%sudo ALL=(ALL:ALL) NOPASSWD:ALL"
    validate: /usr/sbin/visudo -cf %s
    state: present