packages:
- git
- vim
- tmux
- net-tools
- wget
- rsync
- rclone
- zip
- unzip
- pv
- build-essential
- gcc
- g++
- python3-dev
- python3-pip
- python3-venv
- libssl-dev
- libffi-dev
- libxml2-dev
- libxslt1-dev
- zlib1g-dev
- libcurl4-openssl-dev
- libbz2-dev
- liblzma-dev
- openjdk-11-jre
- libdbi-perl
- librocksdb-dev