---
- name: "Update and upgrade apt packages"
  become: true
  apt:
    update_cache: yes
    upgrade: yes
    # autoremove: yes
    # autoclean: yes
    cache_valid_time: 86400

- name: "Install main packages"
  become: true
  apt:
    update_cache: yes
    # autoremove: yes
    # autoclean: yes
    install_recommends: no
    name: "{{ apt_packages }}"
    state: present