---
- name: "Install python dependencies"
  become: true
  pip:
    name: "{{ item }}"
  loop:
    - lxml

- name: "Create annotation.sh"
  template:
    src: annotation.sh.j2
    dest: "{{ annotation_dir }}/annotation.sh"
    mode: 0775

- name: "Create config.json"
  template:
    src: config.json.j2
    dest: "{{ annotation_dir }}/config.json"
    mode: 0644

- name: Download annotation from Maven Central
  community.general.maven_artifact:
    group_id: org.forome
    artifact_id: annotations
    dest: "{{ annotation_dir }}/annotation.jar"

- name: "Download foreground annotation from bucket"
  get_url:
    url: "{{ endpoint_url }}/{{ bucket_annotation }}/data/annotation/annotation_foreground.jar"
    dest: "{{ annotation_dir }}/annotation_foreground.jar"
    tmp_dest: "{{ downloads_dir }}"
