---
- name: Ensure boto3 and botocore modules are installed
  pip:
    name: "{{ item }}"
  with_items:
    - boto3
    - botocore

- name: Set permissions for {{ destlocation }}
  become: true
  file:
    path: "{{ destlocation }}"
    state: directory
    mode: 0755
    owner: "{{ lookup('vars','ansible_user') }}"
    group: "{{ lookup('vars','ansible_user') }}"

- name: Get the list of files first
  amazon.aws.aws_s3:
    profile: "{{ profile }}"
    bucket: "{{ bucket }}"
    mode: list
    prefix: "{{ prefix }}"
    s3_url: "{{ s3_url }}"
  register: listresult
- name: Get the list of Directories
  set_fact: 
    directories: '{%if item is not none %}{{ directories }} + [ "{{ item }}" ] {% else %}{{directories}}{% endif %}'
  with_items: "{{ listresult.s3_keys | map('regex_search', '^.+\/$') }}"
- name: Get the list of Files
  set_fact: 
    files: '{%if item is not none %}{{ files }} + [ "{{ item }}" ] {% else %}{{files}}{% endif %}'
  with_items: "{{ listresult.s3_keys | map('regex_search', '^.+[^\/]$') }}"
- name: Create the directories first
  shell: |
    mkdir -p {{ item }}
  args:
    chdir: "{{ destlocation }}"
  with_items: "{{ directories }}"
- name: GET/DOWNLOAD file from S3 bucket
  amazon.aws.aws_s3:
    profile: "{{ profile }}"
    bucket: "{{ bucket }}"
    mode: get
    overwrite: different
    object: "{{ item }}"
    dest: "{{ destlocation }}/{{ item }}"
    s3_url: "{{ s3_url }}"
  register: getresult
  with_items: "{{ files }}"
- debug: 
    msg="{{ getresult.msg }}" 
  when: getresult.changed