---
aws_access_key: "{{ lookup('env','AWS_ACCESS_KEY_ID') }}"
aws_secret_key: "{{ lookup('env','AWS_SECRET_ACCESS_KEY') }}"
frontend_apikey: "{{ lookup('env','FRONTEND_APIKEY') }}"
slack_webhook: "{{ lookup('env','SLACK_WEBHOOK') }}"
slack_channel: "{{ lookup('env','SLACK_CHANNEL') }}"
mysql_user: "{{ lookup('env','MYSQL_USER') }}"
mysql_password: "{{ lookup('env','MYSQL_PASSWORD') }}"
azure_pat: "{{ lookup('env','AZURE_PAT') }}"
azure_org: "{{ lookup('env','AZURE_ORG') }}"
azure_prj: "{{ lookup('env','AZURE_PRJ') }}"
azure_callback_pipeline_id: "{{ lookup('env','AZURE_CALLBACK_PIPELINE_ID') }}"
bucket_annotation: "forome-annotation"
bucket_dataset: "forome-dataset-public"
endpoint_url: "https://s3.us-south.cloud-object-storage.appdomain.cloud"
data_dir: "/data"
cases_dir: "{{ data_dir }}/cases"
downloads_dir: "{{ data_dir }}/downloads"
astorage_dir: "{{ data_dir }}/astorage"
annotation_dir: "{{ data_dir }}/annotation"
py_venv: "{{ astorage_dir }}/venv"
py_requirements: "/data/astorage/Anfisa-Annotations/requirements.txt"
annotation_src: "{{ astorage_dir }}/Anfisa-Annotations/annotation-service"
mysql_datadir: "{{ data_dir }}/var/lib"
mysql_host: "localhost"
mysql_port: 3306
uwsgi_host: "localhost"
uwsgi_port: 8290
nginx_host: "localhost"
nginx_port: 80
annotation_git_repo: "https://github.com/ForomePlatform/Anfisa-Annotations.git"
annotation_git_branch: "master"
forome_tools_git_repo: "https://github.com/ForomePlatform/forome_misc_tools"
mysqldump: "mysqldump.sql.gz"
# mysqldump: "mysqldump_stub.sql.gz"
data:
  - annotation-hg37_fullpath.tar.gz
  - annotation-hg38_fullpath.tar.gz
  - schema_fullpath.tar.gz
  - rdbs_fullpath.tar.gz
  # - annotation-hg37_fullpath_stub.tar.gz
  # - annotation-hg38_fullpath_stub.tar.gz
  # - schema_fullpath_stub.tar.gz
  # - rdbs_fullpath_stub.tar.gz
datasets:
  - pgp3140_wgs_hlpanel.tar.gz
  - pgp3140_wgs_nist1696.tar.gz
  - pgp3140_wgs_rtg1997.tar.gz