---
- name: Set permissions for {{ destlocation }}
  become: true
  file:
    path: "{{ destlocation }}"
    state: directory
    mode: 0755
    owner: "{{ lookup('vars','ansible_user') }}"
    group: "{{ lookup('vars','ansible_user') }}"

- name: aws s3 sync {{ bucket }} to {{ destlocation }}
  shell: aws --endpoint-url {{ endpoint_url }} s3 sync s3://{{ bucket }}{{ destlocation }} {{ destlocation }}
  async: 9999
  poll: 0
  register: result
- name: Check aws s3 sync status
  async_status:
    jid: "{{ result.ansible_job_id }}"
  register: job_result
  until: job_result.finished
  retries: 9999
  delay: 10
- name: Debug async status
  debug:
    var: job_result.stdout_lines
  when: job_result is defined