---
- name: Installing Mysql and dependencies
  become: true
  package:
    name: "{{ item }}"
    state: present
    update_cache: yes
  with_items: "{{ packages }}"
  notify:
  - Start mysql

- name: creating mysql users
  mysql_user:
    name: "{{ item }}"
    password: "{{ item }}"
    priv: '*.*:ALL'
    host: 'localhost'
    state: present
  with_items: "{{ users }}"
  notify:
  - Unarchive dump