---
- name: "Installing Mysql and dependencies"
  become: true
  package:
    name: "{{ item }}"
    state: present
    update_cache: yes
  loop:
    - mysql-server
    - mysql-client 
    - python3-mysqldb
    - libmysqlclient-dev
  register: mysql_install

- name: "Stop mysql service"
  become: true
  service:
    name: mysql
    state: stopped
  register: mysql_stopped
  when: mysql_install.changed

- name: "Copy /var/lib/mysql to /mnt/var/mysql"
  become: true
  shell: rsync -av /var/lib/mysql /mnt/var/
  register: mysql_var
  when: mysql_stopped.changed

- name: "Edit mysql config"
  become: true
  lineinfile:
    dest: /etc/mysql/mysql.conf.d/mysqld.cnf
    regexp: "^# datadir"
    line: "datadir = /mnt/var/mysql"
    state: present
  register: mysql_config
  when: mysql_var.changed

- name: "Edit apparmor config"
  become: true
  replace:
    path: /etc/apparmor.d/usr.sbin.mysqld
    regexp: '^\s+/var/lib/mysql/(.*)$'
    replace: '  /mnt/var/mysql/\1'
    backup: yes
  register: apparmor
  when: mysql_config.changed

- name: "Restart apparmor"
  become: true
  service:
    name: apparmor
    state: restarted
  when: apparmor.changed

- name: "Restart mysql"
  become: true
  service:
    name: mysql
    state: restarted
  when: mysql_config.changed

- name: "Creating mysql user {{ mysql_user }}"
  become: true
  mysql_user:
    name: "{{ mysql_user }}"
    password: "{{ mysql_password }}"
    priv: '*.*:ALL'
    host: 'localhost'
    state: present

- name: "Download mysqldump.sql.gz"
  amazon.aws.aws_s3:
    bucket: "{{bucket_annotation}}"
    object: "mysqldump.sql.gz"
    dest: "{{ download_dir }}/mysqldump.sql.gz"
    mode: get
    overwrite: different
    s3_url: "{{ endpoint_url }}"
  register: download_mysqldump

# - name: "Create mysql.sh"
#   template:
#     src: mysql.sh.j2
#     dest: "{{ data_dir }}/.scripts/mysql.sh"
#     mode: 0775

# - name: "Run mysqlrestore.sh in background"
#   become: true
#   shell: nohup "{{ data_dir }}/mysqlrestore.sh" &
#   async: 10
#   poll: 0

# - name: "Restore mysqldump"
#   become: true
#   community.mysql.mysql_db:
#     name: all
#     state: import
#     target: "{{ download_dir }}/mysqldump.sql.gz"
#   when: download_mysqldump.changed