---
- name: Install boto3 and botocore modules
  pip:
    name: "{{ item }}"
    state: present
  loop:
    - boto3
    - botocore

- name: Installing Mysql and dependencies
  become: true
  package:
    name: "{{ item }}"
    state: present
    update_cache: yes
  loop:
  - mysql-server
  - mysql-client 
  - python3-mysqldb
  - libmysqlclient-dev
  notify: start mysql

- name: Creating mysql user {{ user }}
  become: true
  mysql_user:
    name: "{{ user }}"
    password: "{{ user }}"
    priv: '*.*:ALL'
    host: 'localhost'
    state: present

- name: Prepare directory {{ destlocation }}
  become: true
  file:
    path: "{{ destlocation }}"
    state: directory
    mode: 0775
    owner: "{{ lookup('vars','ansible_user') }}"
    group: "{{ lookup('vars','ansible_user') }}"

- name: Download {{ mysqlarch }}
  amazon.aws.aws_s3:
    bucket: "{{ bucket }}"
    object: "{{ mysqlarch }}"
    dest: "{{ destlocation }}{{ mysqlarch }}"
    mode: get
    overwrite: different
    s3_url: "{{ endpoint_url }}"
  register: mysqlarch_download

- name: Unarchive {{ mysqlarch }}
  unarchive:
    src: "{{ destlocation }}{{ mysqlarch }}"
    dest: "{{ destlocation }}"
    remote_src: yes
  when: mysqlarch_download.changed
  notify: restore mysqldump