---
- name: "Install virtualenv"
  become: true
  pip:
    name: virtualenv
    executable: pip3

- name: "Install wheel"
  pip:
    name: wheel
    virtualenv: "{{ py_venv }}"

- name: "Install Cython"
  pip:
    name: Cython
    virtualenv: "{{ py_venv }}"

- name: "Install packages"
  pip:
    name: "{{ item }}"
    virtualenv: "{{ py_venv }}"
  loop:
    - setuptools==58.0.0
    - "{{ astorage_dir }}/Anfisa-Annotations/a_storage/plainrocks/"
    - cwlref-runner
    - pymongo
    - mysql-connector-python

- name: "Install requirements"
  pip:
    requirements: "{{ py_requirements }}"
    virtualenv: "{{ py_venv }}"

# - name: "Download forome_tools"
#   get_url:
#     url: "{{ forome_tools_url }}"
#     dest: "/tmp/{{ forome_tools_whl }}.gz"
#   register: forome_tools_download

# - name: "Unarchive forome_tools"
#   shell: "[[ -e /tmp/{{ forome_tools_whl }} ]] || rm -f /tmp/{{ forome_tools_whl }} && gunzip /tmp/{{ forome_tools_whl }}.gz"
#   register: forome_tools_unarchive
#   when: forome_tools_download.changed

- name: "Install forome_tools"
  pip:
    # name: "/tmp/{{ forome_tools_whl }}"
    name: git+https://github.com/ForomePlatform/forome_misc_tools.git#egg=forome-tools
    virtualenv: "{{ py_venv }}"
  # when: forome_tools_unarchive.changed