variable "basename" {}
variable "region" {}
variable "zone" {}
variable "vpc" {}
variable "subnet" {}
variable "security_group" {}
variable "resource_group" {}
variable "instance_name" {}
variable "instance_profile" {}
variable "volume_profile" {}
variable "volume_capacity" {}
variable "user_name" {}
variable "disk_name" {}
variable "ssh_key_id" {}
variable "ssh_public_key" {}
variable "ssh_public_key_file" {}