variable "ibmcloud_api_key" {}
variable "basename" {}
variable "region" {}
variable "zone" {}
variable "vpc" {}
variable "subnet" {}
variable "security_group" {}
variable "resource_group" {}
variable "instance_name" {}
variable "instance_profile" {}
variable "var_volume_profile" {}
variable "var_volume_capacity" {}
variable "data_volume_profile" {}
variable "data_volume_capacity" {}
variable "user_name" {}
variable "var_disk_name" {}
variable "data_disk_name" {}
variable "ssh_key_id" {}
variable "ssh_public_key" {}
variable "ssh_public_key_file" {}