---
- name: "Install python docker"
  become: true
  pip:
    name: docker

- name: "Git clone"
  ansible.builtin.git:
    repo: https://github.com/ForomePlatform/Anfisa-Annotations.git
    dest: /data/astorage/Anfisa-Annotations
    version: develop
    force: yes

- name: "Clear previous build {{ annotation_src }}/build"
  become: true
  file:
    path: "{{ annotation_src }}/build"
    state: absent

- name: "Start gradle container"
  community.docker.docker_container:
    name: gradle
    image: gradle:6.9.2-jdk11
    user: "{{ ansible_user_uid }}:{{ ansible_user_gid }}"
    auto_remove: yes
    volumes:
    - "{{ annotation_src }}:/home/gradle"
    command: >
      /bin/bash -c "gradle clean build -Pfilename=annotation.jar"
  register: gradle_status

- name: "Save gradle container status"
  set_fact:
    gradle_pid: "{{ gradle_status.container.State.Pid }}"

- name: "Wait for gradle build (container PID: {{ gradle_pid }})"
  wait_for:
    path: "/proc/{{ gradle_pid }}/status"
    state: absent

- name: Prepare directory {{ annotation_dst }}
  become: true
  file:
    path: "{{ annotation_dst }}"
    state: directory
    owner: "{{ user }}"
    group: "{{ user }}"
    mode: 0775

- name: "Copy {{ annotation_src }}/build/libs/annotation.jar to {{ annotation_dst }}/annotation.jar"
  copy:
    src: "{{ annotation_src }}/build/libs/annotation.jar"
    dest: "{{ annotation_dst }}/annotation.jar"
    remote_src: yes
    mode: 0775

- name: "Create annotation.sh"
  template:
    src: annotation.sh.j2
    dest: "{{ annotation_dst }}/annotation.sh"
    mode: 0775

- name: "Create config.json"
  template:
    src: config.json.j2
    dest: "{{ annotation_dst }}/config.json"
    mode: 0644