---
- name: Prepare directory /data/annotation
  become: true
  file:
    path: /data/annotation
    state: directory
    owner: "{{ user }}"
    group: "{{ user }}"
    mode: 0775

- name: Create config.json
  template:
      src: config.json.j2
      dest: /data/annotation/config.json
      mode: 0644

- name: Create annotation.sh
  template:
      src: annotation.sh
      dest: /data/annotation/annotation.sh
      mode: 0775