---
- name: "Install python dependencies"
  become: true
  pip:
    name: "{{ item }}"
  loop:
    # - docker
    - lxml

# - name: "Git clone {{ annotation_git_repo }}"
#   ansible.builtin.git:
#     repo: "{{ annotation_git_repo }}"
#     dest: "{{ astorage_dir }}/Anfisa-Annotations"
#     version: "{{ annotation_git_branch }}"
#     force: yes

# - name: "Clear previous build {{ annotation_src }}/build"
#   become: true
#   file:
#     path: "{{ annotation_src }}/build"
#     state: absent

# # - name: "Start gradle container"
# #   community.docker.docker_container:
# #     name: gradle
# #     image: gradle:6.9.2-jdk11
# #     user: "{{ ansible_user_uid }}:{{ ansible_user_gid }}"
# #     auto_remove: yes
# #     volumes:
# #     - "{{ annotation_src }}:/home/gradle"
# #     command: >
# #       /bin/bash -c "gradle clean build -Pfilename=annotation.jar"
# #   register: gradle_status

# # - name: "Save gradle container status"
# #   set_fact:
# #     gradle_pid: "{{ gradle_status.container.State.Pid }}"

# # - name: "Wait for gradle build (container PID: {{ gradle_pid }})"
# #   wait_for:
# #     path: "/proc/{{ gradle_pid }}/status"
# #     state: absent

# - name: Prepare directory {{ annotation_dir }}
#   become: true
#   file:
#     path: "{{ annotation_dir }}"
#     state: directory
#     owner: "{{ user }}"
#     group: "{{ user }}"
#     mode: 0775

# # - name: "Copy {{ annotation_src }}/build/libs/annotation.jar to {{ annotation_dir }}/annotation.jar"
# #   copy:
# #     src: "{{ annotation_src }}/build/libs/annotation.jar"
# #     dest: "{{ annotation_dir }}/annotation.jar"
# #     remote_src: yes
# #     mode: 0775

- name: "Create annotation.sh"
  template:
    src: annotation.sh.j2
    dest: "{{ annotation_dir }}/annotation.sh"
    mode: 0775

- name: "Create config.json"
  template:
    src: config.json.j2
    dest: "{{ annotation_dir }}/config.json"
    mode: 0644

- name: Download annotation from Maven Central
  community.general.maven_artifact:
    group_id: org.forome
    artifact_id: annotations
    dest: /data/annotation/annotation.jar