---
- name: Install boto3 and botocore modules
  pip:
    name: "{{ item }}"
    state: present
  loop:
    - boto3
    - botocore

- name: Prepare directory {{ cases_path }}
  become: true
  file:
    path: "{{ cases_path }}"
    state: directory
    mode: 0775
    owner: "{{ user }}"
    group: "{{ user }}"

- name: Download datasets
  amazon.aws.aws_s3:
    bucket: "{{ bucket }}"
    object: "{{ item }}"
    dest: "{{ cases_path }}{{ item }}"
    mode: get
    overwrite: different
    s3_url: "{{ endpoint_url }}"
  loop: "{{ datasets }}"
  register: download_datasets

- name: Extract archives
  ansible.builtin.unarchive:
    src: "{{ cases_path }}{{ item }}"
    dest: "{{ cases_path }}"
    remote_src: yes
  loop: "{{ datasets }}"
  when: download_datasets.changed
