---
- name: "Download datasets archives"
  amazon.aws.aws_s3:
    bucket: "{{ bucket_dataset }}"
    s3_url: "{{ endpoint_url }}"
    object: "{{ item }}"
    dest: "{{ download_dir }}/{{ item }}"
    mode: get
    overwrite: different
  loop: "{{ datasets }}"
  register: download_datasets

- name: "Extract datasets archives"
  ansible.builtin.unarchive:
    src: "{{ download_dir }}/{{ item }}"
    dest: "{{ cases_dir }}"
    remote_src: yes
  loop: "{{ datasets }}"
  when: download_datasets.changed
