---
- name: Ensure boto3 and botocore modules are installed
  pip:
    name: "{{ item }}"
    state: present
  with_items:
    - boto3
    - botocore

- name: Prepare directory {{ cases_path }}
  become: true
  file:
    path: "{{ cases_path }}"
    state: directory
    mode: 0755
    owner: "{{ lookup('vars','ansible_user') }}"
    group: "{{ lookup('vars','ansible_user') }}"

- name: Download datasets
  amazon.aws.aws_s3:
    bucket: "{{ bucket }}"
    object: "{{ item }}"
    dest: "{{ cases_path }}{{ item }}"
    mode: get
    overwrite: different
    s3_url: "{{ endpoint_url }}"
  with_items: "{{ datasets }}"
  register: download_datasets

- name: Extract archives
  ansible.builtin.unarchive:
    src: "{{ cases_path }}{{ item }}"
    dest: "{{ cases_path }}"
    remote_src: yes
  with_items: "{{ datasets }}"
  when: download_datasets.changed
