---
- name: "Install boto3 and botocore modules"
  pip:
    name: "{{ item }}"
    state: present
  loop:
    - boto3
    - botocore

- name: "Prepare directories"
  become: true
  file:
    path: "{{ item }}"
    state: directory
    mode: 0775
    owner: "{{ user }}"
    group: "{{ user }}"
  loop:
    - "{{ download_dir }}"
    - "{{ cases_dir }}"

- name: "Download datasets"
  amazon.aws.aws_s3:
    bucket: "{{ bucket_dataset }}"
    s3_url: "{{ endpoint_url }}"
    object: "{{ item }}"
    dest: "{{ download_dir }}/{{ item }}"
    mode: get
    overwrite: different
  loop: "{{ datasets }}"
  register: download_datasets

- name: "Extract archives"
  ansible.builtin.unarchive:
    src: "{{ download_dir }}/{{ item }}"
    dest: "{{ cases_dir }}"
    remote_src: yes
  loop: "{{ datasets }}"
  when: download_datasets.changed
