---
- hosts: all
  gather_facts: no

  pre_tasks:

    - name: "Wait for SSH"
      wait_for:
        port: 22
        host: "{{ (ansible_ssh_host|default(ansible_host))|default(inventory_hostname) }}"
        search_regex: OpenSSH
        timeout: 600
      connection: local
      tags: 'always'

    - name: "Set local user"
      set_fact:
        user: "{{ lookup('env', 'USER') }}"
      when: ansible_connection == 'local'
      tags: 'always'

    - name: "Set remote user"
      set_fact:
        user: "{{ (ansible_user|default(remote_user))|default(ansible_ssh_user) }}"
        # user: "{{ lookup('vars', 'ansible_user' }}"
      when: ansible_connection != 'local'
      tags: 'always'

    - name: "Gathering facts"
      setup:
      tags: 'always'

  roles:
    - { role: users, tags: ['users'], when: ansible_connection != 'local' }
    - { role: apt, tags: ['apt'] }
    - { role: docker, tags: ['docker']}
    - { role: prepdir, tags: ['prepdir'] }
    - { role: pipdep, tags: ['pipdep'] }
    - { role: awscli, tags: ['awscli'], when: callback | default(false) | bool == true }
    - { role: mysql, tags: ['mysql'] }
    - { role: data, tags: ['data'], when: callback | default(false) | bool == false }
    - { role: datasets, tags: ['datasets'] }
    - { role: nginx, tags: ['nginx'] }
    - { role: python, tags: ['python'] }
    - { role: astorage, tags: ['astorage'] }
    - { role: annotation, tags: ['annotation'] }
    - { role: callback, tags: ['callback'], when: callback | default(false) | bool }