---
- hosts: all
  gather_facts: no

  pre_tasks:

    - name: "Wait for SSH"
      wait_for:
        port: 22
        host: "{{ (ansible_ssh_host|default(ansible_host))|default(inventory_hostname) }}"
        search_regex: OpenSSH
        timeout: 600
      connection: local

    - name: "Gathering facts"
      setup:

  roles:
    - role: users
      when: ansible_connection != local
    - role: apt
    - role: docker
    - role: prepdir
    - role: pipdep
    - role: awscli
      when: ansible_connection != local
    - role: mysql
    - role: data
      when: callback | default(false) | bool == false
    - role: datasets
    - role: nginx
    - role: python
    - role: astorage
    - role: annotation
    - role: callback
      when: callback | default(false) | bool