---
- name: "Update and upgrade apt packages"
  become: true
  apt:
    update_cache: yes
    upgrade: yes
    autoremove: yes
    autoclean: yes
    cache_valid_time: 86400

- name: "Install main packages"
  become: true
  apt:
    update_cache: yes
    autoremove: yes
    autoclean: yes
    install_recommends: no
    name: "{{ item }}"
    state: present
  loop:
    - git
    - vim
    - tmux
    - net-tools
    - wget
    - rsync
    - rclone
    - zip
    - unzip
    - pv
    - build-essential
    - gcc
    - g++
    - python3
    - python3-dev
    - python3-pip
    - python3-venv
    - libssl-dev
    - libffi-dev
    - libxml2-dev
    - libxslt1-dev
    - zlib1g-dev
    - libcurl4-openssl-dev
    - libbz2-dev
    - liblzma-dev
    - openjdk-11-jre
    - libdbi-perl
    - librocksdb-dev

- name: "Check if reboot required"
  stat:
    path: /var/run/reboot-required
  register: reboot_required_file

- name: "Reboot due to apt needs"
  become: true
  reboot:
    reboot_timeout: 600
  when: reboot_required_file.stat.exists == true and ansible_connection != 'local'