---
- name: Install Docker dependencies
  become: true
  apt:
    name: "{{ item }}"
    update_cache: yes
    state: present
  loop:
    - ca-certificates
    - curl
    - gnupg
    - software-properties-common

- name: Add Docker GPG key
  become: true
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Add Docker Repository
  become: true
  apt_repository:
    # repo: deb https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable
    repo: deb https://download.docker.com/linux/ubuntu focal stable
    state: present

- name: Install Docker
  become: true
  apt:
    name: "{{ item }}"
    update_cache: yes
    state: latest
  loop:
    - docker-ce
    - docker-ce-cli
    - containerd.io

- name: Install Docker-compose
  become: true
  get_url:
    # url : https://github.com/docker/compose/releases/download/1.29.2/docker-compose-{{ ansible_system }}-{{ ansible_architecture }}
    url : https://github.com/docker/compose/releases/download/1.29.2/docker-compose-Linux-x86_64
    dest: /usr/local/bin/docker-compose
    mode: 'u+x,g+x'

- name: Add user to "docker" group
  become: true
  user:
   name: "{{ user }}"
   groups: docker
  # notify: Reboot