---
- name: start mysql
  become: true
  service:
    name: mysql
    state: started
    enabled: yes
- name: restart mysql
  become: true
  service:
    name: mysql
    state: restarted
- name: restore mysqldump
  become: true
  shell: "mysql < {{ destlocation }}{{ mysqldump }}"