#cloud-config
bootcmd:
- mkdir -p /data
- while [ ! -b $(readlink -f ${disk_name}) ]; do echo "waiting for device ${disk_name}"; sleep 5 ; done
- printf 'g\nn\n1\n\n\nw' | fdisk ${disk_name}
- mkfs.ext4 ${disk_name}1 -L data
mounts:
- [ "LABEL=data", "/data", "ext4", "defaults", "0", "0" ]
users:
- default
- name: ${user_name}
  shell: '/bin/bash'
  sudo: ['ALL=(ALL:ALL) NOPASSWD:ALL']
  groups: sudo
  ssh-authorized-keys:
  - ${ssh_public_key}
package_update: true
package_upgrade: true
package_reboot_if_required: false
packages:
- vim
- tmux
- python3