#cloud-config
bootcmd:
- while [ ! -b $(readlink -f ${var_disk_name}) ]; do echo "waiting for device ${var_disk_name}"; sleep 5 ; done
- while [ ! -b $(readlink -f ${data_disk_name}) ]; do echo "waiting for device ${data_disk_name}"; sleep 5 ; done
- printf 'g\nn\n1\n\n\nw' | fdisk ${var_disk_name}
- printf 'g\nn\n1\n\n\nw' | fdisk ${data_disk_name}
- mkfs.ext4 ${var_disk_name}1 -L var
- mkfs.ext4 ${data_disk_name}1 -L data
# - mount ${var_disk_name}1 /mnt
# - rsync -aulvXpogtr /var/lib/* /mnt
# - umount /mnt
# - rm -rf /var/lib
# - mkdir /var/lib
- mkdir -p /data
- mkdir -p /mnt/var
mounts:
- [ "LABEL=data", "/data", "ext4", "defaults", "0", "1" ]
- [ "LABEL=var", "/mnt/var", "ext4", "defaults,noatime,nofail", "0", "2" ]
# - [ "LABEL=var", "/var/lib", "ext4", "defaults,noatime,nofail", "0", "2" ]
users:
- default
- name: ${user_name}
  shell: '/bin/bash'
  sudo: ['ALL=(ALL:ALL) NOPASSWD:ALL']
  groups: sudo
  ssh-authorized-keys:
  - ${ssh_public_key}
# package_update: true
# package_upgrade: false
# package_reboot_if_required: false
# packages:
# - vim
# - tmux
# - rsync
# - python3