#cloud-config
bootcmd:
- mkdir -p /data
- while [ ! -b $(readlink -f ${var_disk_name}) ]; do echo "waiting for device ${var_disk_name}"; sleep 5 ; done
- while [ ! -b $(readlink -f ${data_disk_name}) ]; do echo "waiting for device ${data_disk_name}"; sleep 5 ; done
- printf 'g\nn\n1\n\n\nw' | fdisk ${var_disk_name}
- printf 'g\nn\n1\n\n\nw' | fdisk ${data_disk_name}
- mkfs.ext4 ${var_disk_name}1 -L var
- mkfs.ext4 ${data_disk_name}1 -L data
mounts:
- [ "LABEL=var", "/var/lib/mysql", "ext4", "defaults", "0", "1" ]
- [ "LABEL=data", "/data", "ext4", "defaults", "0", "1" ]
users:
- default
- name: ${user_name}
  shell: '/bin/bash'
  sudo: ['ALL=(ALL:ALL) NOPASSWD:ALL']
  groups: sudo
  ssh-authorized-keys:
  - ${ssh_public_key}
# package_update: true
# package_upgrade: true
# package_reboot_if_required: true
# packages:
# - vim
# - tmux
# - python3